#!/bin/sh
# vim: set ts=3 sw=3 expandtab :

TEMPLATEDIR=map
SOURCEDIR=core

tools/ftl-expand \
   mod='map_str2dbl' \
   key='character(len=*)' \
   key1='character(len=32)' \
   val='real(dbl)' \
   cmp='strcmpci' \
   use='use base_m; use strutil_m' \
   < $TEMPLATEDIR/map_m.ftl \
   > $SOURCEDIR/map_str2dbl_m.f90


tools/ftl-expand \
   mod='map_str2int' \
   key='character(len=*)' \
   key1='character(len=32)' \
   val='integer' \
   cmp='strcmpci' \
   use='use strutil_m' \
   < $TEMPLATEDIR/map_m.ftl \
   > $SOURCEDIR/map_str2int_m.f90

